### ISSUE TITLE
Feature request: Multi-column display

### ISSUE THREAD

**Issue by Strykar** [The-Kid-Gid/nextinspace#1]
4 to 5 columns could easily fit on a 32" monitor @ 1440p resolution.
Any chance of getting to to print more than 1 column?

**Comment by The-Kid-Gid** [comment]
Possibly, but 90ish column line length seems to be the standard for readability with regard to terminal applications. Also, with the way the info is currently printed, it would require a rewrite of the whole display functionality.

I could see maybe adding a feature where the terminal width is detected and output is formatted accordingly.

**Comment by The-Kid-Gid** [comment]
Labeling this as wontfix for now (might revisit)
