### ISSUE TITLE
Feature Request: I've made an Arch Linux PKGBUILD for this, can I put it on the AUR?

### ISSUE THREAD

**Issue by Finermeerkat137** [The-Kid-Gid/nextinspace#4]
I just wanted your permission if I could do this :)

**Comment by The-Kid-Gid** [comment]
I'm pretty sure [there already is one](https://aur.archlinux.org/packages/nextinspace/), but you are free to make one of your own. I think that it's fantastic that people like this project enough to want to contribute!

**Comment by Finermeerkat137** [comment]
Oh that's cool, thanks!
