### ISSUE TITLE
Catch the ratelimit exception

### ISSUE THREAD

**Issue by derkweijers** [The-Kid-Gid/nextinspace#7]
```python
Traceback (most recent call last):
  File "/Users/derkweijers/.pyenv/versions/3.9.0/lib/python3.9/site-packages/nextinspace/api.py", line 230, in get_data
    response.raise_for_status()
  File "/Users/derkweijers/.pyenv/versions/3.9.0/lib/python3.9/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://ll.thespacedevs.com/2.0.0/event/upcoming/?limit=1
```

I think it would be nicer to catch the ratelimit exception and return a cleaner error :)

**Comment by The-Kid-Gid** [comment]
I believe this is already caught, I think I may have just left a debugging `traceback.print_exc()` statement in the relevant code. However, above the traceback can you confirm that there is an `nextinspace: error: GET request failed`? And if not please check your version.

**Comment by The-Kid-Gid** [comment]
See #5

**Comment by derkweijers** [comment]
Ah check. 

IMHO it would be nice to show something like "you've hit the rate limit, try again later". But that's just preference :). Feel free to close this issue and keep it as is!
